# Trigger the pipeline on changes to the devops branch
trigger:
  branches:
    include:
      - devops
  paths:
    include:
      - src/*
    exclude:
      - infra/*
      - app-infra/*
      - bootstrap-backend/*

# Define the agent pool to run the pipeline
pool:
  vmImage: 'windows-latest'

steps:
# Checkout the repository
- checkout: self
  persistCredentials: true

# Use the latest .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Adjust to your .NET version if needed

# Restore dependencies for the solution file
- task: DotNetCoreCLI@2
  displayName: 'Restore dependencies'
  inputs:
    command: 'restore'
    projects: 'src/Azure-demo-app/Azure-demo-app.sln'

# Build the project
- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: 'src/Azure-demo-app/Azure-demo-app.sln'
    arguments: '--configuration Release --no-restore'

# Run tests (if you have them)
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'src/Azure-demo-app/Azure-demo-app.sln'
    arguments: '--configuration Release --no-build --no-restore'

# Publish the app
- task: DotNetCoreCLI@2
  displayName: 'Publish the app'
  inputs:
    command: 'publish'
    projects: 'src/Azure-demo-app/Azure-demo-app.sln'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/app --no-restore'
    publishWebProjects: false
    zipAfterPublish: true

# Upload the artifact to Azure DevOps
- task: PublishBuildArtifacts@1
  displayName: 'Upload artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/app'
    artifactName: 'azure-demo-app'
    publishLocation: 'Container'