name: Deploy Azure Web App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore ./src/Azure-demo-app/Azure-demo-app.sln

    - name: Build Web App
      run: dotnet build ./src/Azure-demo-app/Azure-demo-app.sln --configuration Release --no-restore

    - name: Publish Web App
      run: dotnet publish ./src/Azure-demo-app/Azure-demo-app/Azure-demo-app.csproj --configuration Release --output ./publish/web --no-restore

    - name: List published files
      run: ls -R ./publish/web

    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: my-helo-app
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish/web

    - name: Test App URL
      run: curl -I https://my-helo-app.azurewebsites.net